# Generated by Django 4.2.2 on 2023-11-13 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_seller_latitude_alter_seller_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(default=False, upload_to='posters', verbose_name='постер'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=False, max_length=5, verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='seller',
            name='rate',
            field=models.FloatField(default=False, max_length=5, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть ниже нуля')], verbose_name='цена'),
        ),
    ]
