# Generated by Django 4.2.2 on 2023-11-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sellerrating_sellercomment_productrating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-id',), 'verbose_name': 'комментарии к продукту', 'verbose_name_plural': 'комментарии к продуктам'},
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'ordering': ('-id',), 'verbose_name': 'рейтинг к продукту', 'verbose_name_plural': 'рейтинг к продуктам'},
        ),
        migrations.AlterModelOptions(
            name='sellercomment',
            options={'ordering': ('-id',), 'verbose_name': 'комментарии к продавцу', 'verbose_name_plural': 'комментарии к продавцам'},
        ),
        migrations.AlterModelOptions(
            name='sellerrating',
            options={'ordering': ('-id',), 'verbose_name': 'рейтинг к продавцу', 'verbose_name_plural': 'рейтинг к продавцам'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='описание к товару'),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='описание к продавцу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='постер'),
        ),
    ]
