# Generated by Django 4.2.2 on 2023-11-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='rate',
        ),
        migrations.AddField(
            model_name='seller',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='постер'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product', verbose_name='рейтинг к продукту'),
        ),
        migrations.AlterField(
            model_name='sellerrating',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.seller', verbose_name='рейтинг к продавцу'),
        ),
    ]
