# Generated by Django 4.2.2 on 2023-11-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_rate_remove_seller_rate_seller_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0, max_length=5, verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='seller',
            name='rate',
            field=models.FloatField(default=0, max_length=5, verbose_name='рейтинг'),
        ),
    ]
