# Generated by Django 4.2.2 on 2023-12-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='адресс'),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='номер телефона'),
        ),
    ]
